//! `mailo` — the command line. The Dioxus shell will call the same store methods.

pub mod account;
pub mod appearance;
pub mod attach;
pub mod cli;
pub mod compose;
pub mod contacts;
mod contrast;
pub mod discover;
pub mod editor;
pub mod export;
pub mod folder;
pub mod hover;
pub mod import;
pub mod invite;
pub mod ipc;
pub mod notify;
mod palette;
pub mod password;
pub mod print;
mod provider;
pub mod query;
pub mod reader;
pub mod receipt;
pub mod rules;
pub mod search;
pub mod snooze;
pub mod space;
pub mod sync;
pub mod template;
mod today;
pub mod trust;
pub mod ui;
pub mod undo;
pub mod unsubscribe;
pub mod view;
