//! The shell's stylesheet.
//!
//! Real `.css` files, stitched at compile time. Splitting by concern rather than by line
//! count is what CONVENTIONS.md section 8 asks for: `list.css` is one concept in a way that
//! "lines 25 to 34 of the stylesheet" never is.
//!
//! The order below is the cascade and is load-bearing. Keep it.
//!
//! It is one `concat!` and not several named pieces because `concat!` takes literals only:
//! `include_str!` expands to one, a `const` does not, and a nested `const` fails to compile
//! with "only literals can be passed to `concat!()`". So the dark guards are spelled out
//! here rather than folded into a `TOKENS` of their own.
//!
//! Three rules the files themselves cannot state:
//!
//! - **The dark palette is written once.** `tokens.dark.css` holds bare declarations with no
//!   selector, and it is included twice below: inside the `prefers-color-scheme` guard, and
//!   inside `:root[data-theme="dark"]`. Three theme states, one source of truth. The guard is
//!   `:root:not([data-theme="light"])` so an explicit light choice beats a dark desktop.
//! - **`accents.css` comes after the dark block.** A light accent block and the dark palette
//!   block are both one attribute deep, so source order is what separates them. The six dark
//!   accent blocks carry a second attribute and win from there regardless -- belt as well as
//!   braces, because this is the failure that looks like "the accent doesn't work in dark".
//! - **Contrast-critical tokens are literal `#rrggbb`.** The contrast test parses them; it
//!   cannot read a `color-mix()`, and it must fail rather than skip when it meets one.
//!   `color-mix()` is for decoration -- hovers, washes, the shadow.

#[cfg(test)]
mod contrast;

pub(super) const STYLE: &str = concat!(
    // First, so every rule after it can name a face. Generated by `build.rs`; see there for
    // why the fonts are `data:` URIs and not files, a handler, or a font host.
    include_str!(concat!(env!("OUT_DIR"), "/fonts.css")),
    include_str!("reset.css"),
    include_str!("tokens.css"),
    "@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n",
    include_str!("tokens.dark.css"),
    "  }\n}\n",
    ":root[data-theme=\"dark\"] {\n",
    include_str!("tokens.dark.css"),
    "}\n",
    include_str!("accents.css"),
    include_str!("shell.css"),
    include_str!("list.css"),
    include_str!("menus.css"),
    include_str!("reader.css"),
    include_str!("composer.css"),
    include_str!("controls.css"),
);

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use super::{STYLE, contrast};
    use crate::view::Accent;

    const ACCENT_KEYS: &[&str] = &["--accent", "--accent-ink", "--accent-soft", "--seal"];

    /// Text on every ground it is drawn on. The Post reference puts faint text on the recessed
    /// panes too (the sidebar's counts, the reader's meta), so `--surface-2` is checked, not
    /// only the paper. `--warn` is a star's fill and a retry's mark, a graphic, so 3.0.
    const PAIRS: &[(&str, &str, f64)] = &[
        ("--ink", "--paper", 4.5),
        ("--ink", "--surface", 4.5),
        ("--ink", "--surface-2", 4.5),
        ("--ink", "--raise", 4.5),
        ("--ink-soft", "--paper", 4.5),
        ("--ink-soft", "--surface", 4.5),
        ("--ink-soft", "--surface-2", 4.5),
        ("--ink-faint", "--paper", 3.0),
        ("--ink-faint", "--surface", 3.0),
        ("--ink-faint", "--surface-2", 3.0),
        ("--danger", "--paper", 4.5),
        ("--danger-ink", "--danger", 4.5),
        ("--accent-ink", "--accent", 4.5),
        ("--accent", "--paper", 3.0),
        ("--accent", "--surface", 3.0),
        ("--ink", "--accent-soft", 4.5),
        ("--warn", "--surface", 3.0),
        ("--ok", "--surface", 3.0),
    ];

    /// Light, then dark because the desktop prefers it, then dark because the
    /// document asked for it. The overlay is the palette laid over bare `:root`;
    /// light has none.
    const THEMES: &[(&str, Option<&str>)] = &[
        ("light", None),
        ("dark (desktop)", Some(r#":root:not([data-theme="light"])"#)),
        ("dark (attribute)", Some(r#":root[data-theme="dark"]"#)),
    ];

    /// Every declaration of every rule whose selector is exactly `selector`, merged in source
    /// order so a later rule wins. Exact comparison, never `contains`: `:root[data-theme="dark"]`
    /// is a prefix of `:root[data-theme="dark"][data-accent="oxblood"]`.
    fn declared(css: &str, selector: &str) -> BTreeMap<String, String> {
        let css = strip_comments(css);
        let mut out = BTreeMap::new();
        declarations_in(&css, selector, &mut out);
        out
    }

    fn declarations_in(css: &str, selector: &str, out: &mut BTreeMap<String, String>) {
        let bytes = css.as_bytes();
        let mut index = 0;
        let mut boundary = 0;
        while index < bytes.len() {
            match bytes[index] {
                b'{' => {
                    let sel = css[boundary..index].trim();
                    let Some(close) = matching_close(css, index) else {
                        return;
                    };
                    // An at-rule is a wrapper. Descend so the rules inside it are visible;
                    // do not record the at-rule itself.
                    if sel.starts_with('@') {
                        declarations_in(&css[index + 1..close], selector, out);
                    } else if sel == selector {
                        record(&css[index + 1..close], out);
                    }
                    index = close + 1;
                    boundary = index;
                }
                b';' | b'}' => {
                    boundary = index + 1;
                    index += 1;
                }
                _ => index += 1,
            }
        }
    }

    fn matching_close(css: &str, open: usize) -> Option<usize> {
        let mut depth = 0usize;
        for (index, byte) in css.as_bytes().iter().enumerate().skip(open) {
            match byte {
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(index);
                    }
                }
                _ => {}
            }
        }
        None
    }

    fn record(body: &str, out: &mut BTreeMap<String, String>) {
        for decl in body.split(';') {
            let Some((name, value)) = decl.split_once(':') else {
                continue;
            };
            let name = name.trim();
            if kept(name) {
                out.insert(name.to_string(), value.trim().to_string());
            }
        }
    }

    fn kept(name: &str) -> bool {
        name.starts_with("--")
            || name == "grid-template-columns"
            || name == "position"
            || name == "grid-column"
    }

    fn strip_comments(css: &str) -> String {
        let mut out = String::with_capacity(css.len());
        let mut chars = css.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '/' && chars.peek() == Some(&'*') {
                chars.next();
                while let Some(d) = chars.next() {
                    if d == '*' && chars.peek() == Some(&'/') {
                        chars.next();
                        break;
                    }
                }
                out.push(' ');
            } else {
                out.push(c);
            }
        }
        out
    }

    /// `Some("--x")` when the whole value is exactly `var(--x)`.
    fn exactly_var(value: &str) -> Option<&str> {
        let inner = value.trim().strip_prefix("var(")?.strip_suffix(')')?.trim();
        if inner.starts_with("--") && !inner.contains(|c: char| c == ',' || c.is_whitespace()) {
            Some(inner)
        } else {
            None
        }
    }

    /// The literal hex a token resolves to, following one `var(--x)` and no further.
    fn literal(tokens: &BTreeMap<String, String>, name: &str) -> Result<String, String> {
        let Some(raw) = tokens.get(name) else {
            return Err(format!("{name} is missing"));
        };
        let resolved = if let Some(target) = exactly_var(raw) {
            let Some(value) = tokens.get(target) else {
                return Err(format!("{name} is var({target}) but {target} is missing"));
            };
            value
        } else {
            raw
        };
        if contrast::ratio(resolved, "#000000").is_none() {
            return Err(format!("{name} is not a hex colour ({resolved})"));
        }
        Ok(resolved.clone())
    }

    fn resolved(overlay: Option<&str>, accent: &str) -> BTreeMap<String, String> {
        let mut tokens = declared(STYLE, ":root");
        if let Some(selector) = overlay {
            tokens.extend(declared(STYLE, selector));
        }
        tokens.extend(declared(STYLE, accent));
        tokens
    }

    fn accent_selector(overlay: Option<&str>, slug: &str) -> String {
        match overlay {
            Some(selector) => format!(r#"{selector}[data-accent="{slug}"]"#),
            None => format!(r#":root[data-accent="{slug}"]"#),
        }
    }

    #[test]
    fn a_dark_token_also_has_a_light_value() {
        let light = declared(STYLE, ":root");
        let dark = declared(STYLE, r#":root[data-theme="dark"]"#);
        let dark_tokens: Vec<&str> = dark
            .keys()
            .filter(|name| name.starts_with("--"))
            .map(String::as_str)
            .collect();
        assert!(
            !dark_tokens.is_empty(),
            "no custom properties on :root[data-theme=\"dark\"]",
        );
        let missing: Vec<&str> = dark_tokens
            .into_iter()
            .filter(|name| !light.contains_key(*name))
            .collect();
        assert!(
            missing.is_empty(),
            "dark palette tokens with no light value: {}",
            missing.join(", "),
        );
    }

    #[test]
    fn an_accent_declares_exactly_the_four() {
        let expect: BTreeSet<&str> = ACCENT_KEYS.iter().copied().collect();
        let mut failures = Vec::new();
        for accent in Accent::ALL {
            let slug = accent.slug();
            for selector in [
                format!(r#":root[data-accent="{slug}"]"#),
                format!(r#":root:not([data-theme="light"])[data-accent="{slug}"]"#),
                format!(r#":root[data-theme="dark"][data-accent="{slug}"]"#),
            ] {
                let decls = declared(STYLE, &selector);
                let got: BTreeSet<&str> = decls.keys().map(String::as_str).collect();
                if got != expect {
                    let missing: Vec<_> = expect.difference(&got).collect();
                    let extra: Vec<_> = got.difference(&expect).collect();
                    failures.push(format!("{selector}: missing {missing:?}, extra {extra:?}"));
                }
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    #[test]
    fn each_swatch_is_its_hues_accent() {
        // Resolved apart from the accent block. A swatch written as `var(--accent)` would
        // equal the hue only when that hue is the one selected, which is the case this
        // exists to forbid.
        let mut failures = Vec::new();
        for &(state, overlay) in THEMES {
            let mut palette = declared(STYLE, ":root");
            if let Some(selector) = overlay {
                palette.extend(declared(STYLE, selector));
            }
            for accent in Accent::ALL {
                let slug = accent.slug();
                let swatch = format!("--swatch-{slug}");
                let block = declared(STYLE, &accent_selector(overlay, slug));
                let swatch_hex = literal(&palette, &swatch);
                let accent_hex = literal(&block, "--accent");
                match (swatch_hex, accent_hex) {
                    (Ok(swatch_hex), Ok(accent_hex)) if swatch_hex == accent_hex => {}
                    (Ok(swatch_hex), Ok(accent_hex)) => failures.push(format!(
                        "{state} {slug}: {swatch} is {swatch_hex}, its --accent is {accent_hex}"
                    )),
                    (swatch_hex, accent_hex) => {
                        if let Err(reason) = &swatch_hex {
                            failures.push(format!("{state} {slug}: {reason}"));
                        }
                        if let Err(reason) = &accent_hex {
                            failures.push(format!("{state} {slug}: {reason}"));
                        }
                    }
                }
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    #[test]
    fn the_decoration_follows_the_dark_palette() {
        // The one-line `color-scheme` rule means `:root[data-theme="dark"]` is the wrong
        // anchor: it occurs before the palette, so the assertion would hold with the files
        // misordered. The desktop guard occurs once, around the palette.
        let Some(palette) = STYLE.rfind(":root:not([data-theme=\"light\"]) {") else {
            panic!("the desktop dark palette selector is missing");
        };
        let Some(decoration) = STYLE.find("[data-accent=") else {
            panic!("no [data-accent= selector");
        };
        assert!(
            decoration > palette,
            "first [data-accent= at {decoration}, last desktop dark palette at {palette}",
        );
    }

    #[test]
    fn the_load_bearing_layout_survives() {
        let app = declared(STYLE, ".app");
        let app_columns = app.get("grid-template-columns").map(String::as_str);
        assert!(
            app_columns.is_some_and(|value| value.contains("minmax(0, 1fr)")),
            ".app grid-template-columns is {app_columns:?}; without minmax(0, 1fr) the grid overflows the window",
        );

        let row = declared(STYLE, ".row");
        let row_columns = row
            .get("grid-template-columns")
            .map(String::as_str)
            .unwrap_or("");
        assert_eq!(
            row_columns.matches("minmax(0,").count(),
            2,
            ".row grid-template-columns is {row_columns:?}; without both minmax(0, …) tracks the grid overflows the window",
        );
        let position = row.get("position").map(String::as_str);
        assert_eq!(
            position,
            Some("relative"),
            ".row position is {position:?}; .hover is positioned against the row",
        );

        let labels = declared(STYLE, ".labels");
        let span = labels.get("grid-column").map(String::as_str);
        assert_eq!(
            span,
            Some("1 / -1"),
            ".labels grid-column is {span:?}; the menus are grid items of the row",
        );
    }

    #[test]
    fn every_pair_is_legible() {
        let mut failures = Vec::new();
        for &(state, overlay) in THEMES {
            for accent in Accent::ALL {
                let slug = accent.slug();
                let tokens = resolved(overlay, &accent_selector(overlay, slug));
                for &(fore, back, need) in PAIRS {
                    let fore_hex = literal(&tokens, fore);
                    let back_hex = literal(&tokens, back);
                    match (fore_hex, back_hex) {
                        (Ok(fore_hex), Ok(back_hex)) => match contrast::ratio(&fore_hex, &back_hex)
                        {
                            Some(measured) if measured < need => failures.push(format!(
                                "{fore} on {back}, {state}, {slug}: {measured:.2} < {need:.1}"
                            )),
                            Some(_) => {}
                            None => failures.push(format!(
                                "{fore} on {back}, {state}, {slug}: {fore} is not a hex colour ({fore_hex}) / {back} ({back_hex})"
                            )),
                        },
                        (fore_hex, back_hex) => {
                            if let Err(reason) = fore_hex {
                                failures.push(format!("{fore} on {back}, {state}, {slug}: {reason}"));
                            }
                            if let Err(reason) = back_hex {
                                failures.push(format!("{fore} on {back}, {state}, {slug}: {reason}"));
                            }
                        }
                    }
                }
            }
        }
        assert!(failures.is_empty(), "{}", failures.join("\n"));
    }

    /// Rules that are not the palette. `:root` holds the hex the contrast test reads,
    /// including when it is nested in `@media`. An at-rule is a wrapper, as in
    /// [`declarations_in`].
    fn component_rules(css: &str, out: &mut Vec<(String, String)>) {
        let bytes = css.as_bytes();
        let mut index = 0;
        let mut boundary = 0;
        while index < bytes.len() {
            match bytes[index] {
                b'{' => {
                    let selector = css[boundary..index].trim();
                    let Some(close) = matching_close(css, index) else {
                        return;
                    };
                    let body = &css[index + 1..close];
                    if selector.starts_with('@') {
                        component_rules(body, out);
                    } else if !selector.is_empty() && !selector.starts_with(":root") {
                        out.push((selector.to_string(), body.to_string()));
                    }
                    index = close + 1;
                    boundary = index;
                }
                b';' | b'}' => {
                    boundary = index + 1;
                    index += 1;
                }
                _ => index += 1,
            }
        }
    }

    /// Letter, digit, or `-`. `_` is a boundary, and so is either end of the text.
    /// Comparison stays case-sensitive: `Canvas` is not `CanvasText`, and `Highlight`
    /// is not `--highlight`.
    fn word_continues(c: char) -> bool {
        c.is_alphanumeric() || c == '-'
    }

    /// What may follow a hex colour without making it part of a longer identifier.
    /// End of input does not continue one.
    fn colour_ident_continues(c: char) -> bool {
        c.is_alphanumeric() || c == '-' || c == '_'
    }

    fn starts_with_at(chars: &[char], index: usize, needle: &str) -> bool {
        let mut rest = chars[index..].iter().copied();
        for expected in needle.chars() {
            if rest.next() != Some(expected) {
                return false;
            }
        }
        true
    }

    /// Length in chars of a `#` plus 3, 4, 6, or 8 hex digits, longest first, when the
    /// next character does not continue an identifier. `None` when `chars[index]` is not
    /// such a colour.
    fn hex_colour_at(chars: &[char], index: usize) -> Option<usize> {
        if chars[index] != '#' {
            return None;
        }
        let mut run = 0usize;
        while chars
            .get(index + 1 + run)
            .is_some_and(|c| c.is_ascii_hexdigit())
        {
            run += 1;
        }
        for len in [8usize, 6, 4, 3] {
            if run < len {
                continue;
            }
            let terminated = chars
                .get(index + 1 + len)
                .is_none_or(|c| !colour_ident_continues(*c));
            if terminated {
                return Some(len + 1);
            }
        }
        None
    }

    fn offence_at(chars: &[char], index: usize) -> Option<String> {
        if let Some(len) = hex_colour_at(chars, index) {
            return Some(chars[index..index + len].iter().collect());
        }
        for name in ["rgba(", "rgb(", "hsl(", "oklch(", "var(--edge)"] {
            if starts_with_at(chars, index, name) {
                return Some(name.to_string());
            }
        }
        if index > 0 && word_continues(chars[index - 1]) {
            return None;
        }
        let mut matched: Option<&str> = None;
        for word in [
            "CanvasText",
            "Canvas",
            "ButtonFace",
            "Highlight",
            "currentColor",
        ] {
            if !starts_with_at(chars, index, word) {
                continue;
            }
            let after = index + word.chars().count();
            let boundary = chars.get(after).is_none_or(|c| !word_continues(*c));
            if boundary && matched.is_none_or(|got| word.len() > got.len()) {
                matched = Some(word);
            }
        }
        matched.map(str::to_string)
    }

    fn colour_offences(selector: &str, body: &str) -> Vec<String> {
        let chars: Vec<char> = body.chars().collect();
        let mut offences = Vec::new();
        let mut index = 0;
        while index < chars.len() {
            if let Some(found) = offence_at(&chars, index) {
                offences.push(format!("{selector}: {found}"));
                index += found.chars().count();
            } else {
                index += 1;
            }
        }
        offences
    }

    /// Every `@font-face` in `css`, as (family, `src`).
    fn font_faces(css: &str) -> Vec<(String, String)> {
        css.split("@font-face")
            .skip(1)
            .filter_map(|rest| {
                let body = &rest[rest.find('{')? + 1..rest.find('}')?];
                // `src` is found by name, not by splitting on `;`: a data URI contains one
                // (`data:font/woff2;base64,`), so a declaration split cuts it in half.
                let family = body.split(';').find_map(|decl| {
                    let (name, value) = decl.split_once(':')?;
                    (name.trim() == "font-family")
                        .then(|| value.trim().trim_matches('"').to_string())
                })?;
                let src = body[body.find("src:")? + "src:".len()..].trim_start();
                Some((family, src.to_string()))
            })
            .collect()
    }

    #[test]
    fn each_font_token_leads_with_a_face_we_ship() {
        let faces = font_faces(STYLE);
        let shipped: BTreeSet<&str> = faces.iter().map(|(family, _)| family.as_str()).collect();
        let tokens = declared(STYLE, ":root");
        for token in ["--font-display", "--font-ui", "--font-data"] {
            let Some(stack) = tokens.get(token) else {
                panic!("{token} is missing");
            };
            let first = stack
                .split(',')
                .next()
                .unwrap_or("")
                .trim()
                .trim_matches('"');
            assert!(
                shipped.contains(first),
                "{token} leads with {first:?}, which no @font-face declares; shipped: {shipped:?}"
            );
        }
        // Three families, each in both subsets; Karla and Space Mono in two styles or weights.
        assert_eq!(faces.len(), 10, "{shipped:?}");
    }

    #[test]
    fn each_face_is_an_embedded_woff2() {
        // "wOF2" is the WOFF2 signature; in base64 it begins "d09GMg". A truncated or
        // mis-encoded file, or a TTF renamed to .woff2, fails here rather than as a silent
        // fallback to the system face that only a screenshot would show.
        for (family, src) in font_faces(STYLE) {
            assert!(
                src.starts_with("url(data:font/woff2;base64,d09GMg"),
                "{family}: {}",
                &src[..src.len().min(48)]
            );
        }
    }

    /// Custom properties a component sets on one element (from markup, per row or per spark),
    /// so they are never on `:root`. Each rule that reads one gives it a fallback or is only
    /// reached with it set.
    const PER_ELEMENT: &[&str] = &["--i", "--a", "--d", "--dy"];

    #[test]
    fn every_var_is_declared() {
        // A misspelt token is not an error anywhere: `var(--line-sfot)` resolves to nothing,
        // the declaration is dropped, and the element quietly takes its inherited value. With
        // hundreds of rules ported from the reference, this is the typo that survives review.
        let css = strip_comments(STYLE);
        let root = declared(&css, ":root");
        let mut missing = BTreeSet::new();
        for (at, _) in css.match_indices("var(--") {
            let name: String = css[at + "var(".len()..]
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '-')
                .collect();
            if !root.contains_key(&name) && !PER_ELEMENT.contains(&name.as_str()) {
                missing.insert(name);
            }
        }
        assert!(missing.is_empty(), "used but never declared: {missing:?}");
    }

    #[test]
    fn no_colour_outside_the_palette() {
        let css = strip_comments(STYLE);
        let mut rules = Vec::new();
        component_rules(&css, &mut rules);
        let mut offences = Vec::new();
        for (selector, body) in &rules {
            offences.extend(colour_offences(selector, body));
        }
        assert!(offences.is_empty(), "{}", offences.join("\n"));
    }
}
